# Cinder driver container for Dell EMC PowerMax
# Using openstack-cinder-volume base image
# Version 1.0.2

FROM registry.redhat.io/rhosp-rhel8/openstack-cinder-volume:16.2

MAINTAINER Dell EMC
LABEL description="Red Hat OpenStack Platform 16.2 cinder-volume Dell EMC PowerMax" \
      summary="Red Hat OpenStack Platform 16.2 cinder-volume Dell EMC PowerMax" \
      name="dellemc/openstack-cinder-volume-pmax-rhosp16" \
      vendor="Dell EMC" \
      version="1.0.2"

USER root
COPY LICENSE /licenses/licensing.txt
COPY cinder/volume/drivers/dell_emc/powermax /usr/lib/python3.6/site-packages/cinder/volume/drivers/dell_emc/powermax
RUN python3 -mcompileall /usr/lib/python3.6/site-packages/cinder/volume/drivers/dell_emc/powermax

USER cinder
